
#|
----------------- b2evolution  user/pwd: admin/vb4sadfA
>> login by accessing 
http://herge.sisl.rites.uic.edu/notamper/instrumented/b2evolution-0.8.6/admin/b2edit.php
>> inst:
http://herge.sisl.rites.uic.edu/notamper/instrumented/b2evolution-0.8.6/blog_a.php?disp=profile

--------------------- WeBid     admin    vb4sadfA
http://herge.sisl.rites.uic.edu/notamper/instrumented/WeBid-0.5.4/register.php

------------------- websubrev
http://herge.sisl.rites.uic.edu/notamper/instrumented/websubrev/webtree/submit/submit.php
|#
(defstruct wavstest name url formid stuburl bl indep (method "post") (multipart nil) unique required)
(defun wavs-tests ()
(list  
 (make-wavstest   ; username: admin  pwd: vb4sadfA
   :name 'b2 
   :url "http://herge.sisl.rites.uic.edu/notamper/instrumented/b2evolution-0.8.6/blog_a.php?disp=profile"  ; url
   :formid "http://herge.sisl.rites.uic.edu/notamper/instrumented/b2evolution-0.8.6/htsrv/profile_update.php" ; identify form
   :stuburl "http://herge.sisl.rites.uic.edu/notamper/instrumented/b2evolution-0.8.6/stub"  ; ajax stub URL
   :indep '(   ; a list of independent components (a partioning of the variables)
	    ((post "checkuser_id"))
	    ((post "newuser_firstname"))
	    ((post "newuser_lastname"))
	    ((post "newuser_nickname"))
	    ((post "newuser_idmode"))
	    ((post "newuser_email"))
	    ((post "newuser_url"))
	    ((post "newuser_icq"))
	    ((post "newuser_aim"))
	    ((post "newuser_msn"))
	    ((post "newuser_yim"))
	    ((post "pass1") (post "pass2"))
	    ((post "submit"))
	    )
   :bl '(((post "checkuser_id") . "1")
	 ((post "newuser_firstname") . "joseph") 
	 ((post "newuser_lastname") . "schmoe")
	 ((post "newuser_nickname") . "joe")
	 ((post "newuser_idmode") . "nickname")
	 ((post "newuser_email") . "joe@schmoe.com")
	 ((post "newuser_url") . "http://joeschmoe.com")
	 ((post "newuser_icq") . "1276")
	 ((post "newuser_aim") . "aim")
	 ((post "newuser_msn") . "msn")
	 ((post "newuser_yim") . "yahoo")
	 ((post "pass1") . "x")
	 ((post "pass2") . "x")
	 ((post "submit") . "Update")))
  ; another possible input...
; TPL_name=aaaa+aaaa&TPL_nick=testme1&TPL_password=thistime&TPL_repeat_password=thistime&TPL_email=test%40test.com&TPL_birthdate=01%2F11%2F1950&TPL_address=ramsay+road&TPL_city=tallital&TPL_prov=uttarnacha&TPL_country=India&TPL_zip=263139&TPL_phone=1111111111&TPL_nletter=1&action=first&TPL_id_hidden=&TPL_nick_hidden=&TPL_password_hidden=&TPL_name_hidden=&TPL_email_hidden=&=Register+now

 (make-wavstest  ; trace analysis runs for > 30 minutes on initial trace
  :name 'bid  ; note username and email need to be unique each time (in addition to declaring them unique)
  :formid 'registration
  :unique '((post "TPL_nick") (post "TPL_email")) 
  :url "http://herge.sisl.rites.uic.edu/notamper/instrumented/WeBid-0.5.4/register.php"
  :stuburl "http://herge.sisl.rites.uic.edu/notamper/instrumented/WeBid-0.5.4/stub"
  :indep '(
	   ((post "TPL_name"))
	   ((post "TPL_nick"))
	   ((post "TPL_password") (post "TPL_repeat_password"))
	   ((post "TPL_email"))
	   ((post "TPL_birthdate"))
	   ((post "TPL_address"))
	   ((post "TPL_city"))
	   ((post "TPL_prov"))
	   ((post "TPL_country"))
	   ((post "TPL_zip"))
	   ((post "TPL_phone"))
	   ((post "TPL_nletter"))
	   ((post "action"))
	   ((post "TPL_id_hidden"))
	   ((post "TPL_nick_hidden"))
	   ((post "TPL_password_hidden"))
	   ((post "TPL_name_hidden"))
	   ((post "TPL_email_hidden")))
  :bl '(((post "TPL_name") . "Joe Schmoe")
	((post "TPL_nick") . "joetest4")
	((post "TPL_password") . "joeystalin")
	((post "TPL_repeat_password") . "joeystalin")
	((post "TPL_email") . "joe4@schmoe.com")
	((post "TPL_birthdate") . "01/19/1900")
	((post "TPL_address") . "123 Bluebird Lane")
	((post "TPL_city") . "Chicago")
	((post "TPL_prov") . "IL")
	((post "TPL_country") . "United States")
	((post "TPL_zip") . "60637")
	((post "TPL_phone") . "555-3456")
	((post "TPL_nletter") . "1")
	((post "action") . "first")
	((post "TPL_id_hidden") . "")
	((post "TPL_nick_hidden") . "")
	((post "TPL_password_hidden") . "")
	((post "TPL_name_hidden") . "")
	((post "TPL_email_hidden") . "")
	))
 (make-wavstest  ; traces look okay, but having some trouble with string solving (types aren't being added)
  :name 'sub 
  :url "http://herge.sisl.rites.uic.edu/notamper/instrumented/websubrev/webtree/submit/submit.php"
  :multipart t
  :formid 'submit
  :stuburl "http://herge.sisl.rites.uic.edu/notamper/instrumented/websubrev/webtree/submit/stub"
  :bl '(((post "MAX_FILE_SIZE") "20000000")
	((post "title") . "Joe's Excellent Paper")
	((post "authors") . "Joe Schmoe and Joseph Stalin")
	((post "affiliations") . "Poe Dunk University, Soviet Union")
	((post "contact") . "joe@schmoe.com, joe@ussr.gov")
	((post "abstract") . "An exceedingly excellent paper on effortless egalitarianism.")
	((post "category") . "security")
	((post "keywords") . "egalitarianism")
	((post "comment") . "Hope it gets in."))
  :indep '(
	   ((post "MAX_FILE_SIZE"))
	   ((post "title"))
	   ((post "authors"))
	   ((post "affiliations"))
	   ((post "contact"))
	   ((post "abstract"))
	   ((post "category"))
	   ((post "keywords"))
	   ((post "comment")))
  )))

; single quotes -> double quotes
; \ -> \\ inside strings
(defparameter csvst 
'((and (is_scalar (post "user_id")) (preg_match "/^(\+|-)?[0-9]+$/" (post "user_id")))
  (PREG_REPLACE "\\r|\\n" "" (TRIM (STRIP_TAGS (post "firstname"))))
  (PREG_REPLACE "\\r|\\n" "" (TRIM (STRIP_TAGS (post "lastname"))))
  (and (NOT (PREG_REPLACE "\\r|\\n" "" (TRIM (STRIP_TAGS (post "nickname")))))
       (not (empty (post "nickname"))))
  (PREG_REPLACE "\\r|\\n" "" (TRIM (STRIP_TAGS (post "idmode"))))
  (PREG_REPLACE "\\r|\\n" "" (TRIM (STRIP_TAGS (post "locale"))))
  (and (PREG_REPLACE "\\r|\\n" "" (TRIM (STRIP_TAGS (post "icq"))))
       (or (empty (post "icq"))
	   (preg_match "^[0-9]+$" (post "icq"))))
  (PREG_REPLACE "\\r|\\n" "" (TRIM (STRIP_TAGS (post "aim"))))
  (PREG_REPLACE "\\r|\\n" "" (TRIM (STRIP_TAGS (post "msn"))))
  (PREG_REPLACE "\\r|\\n" "" (TRIM (STRIP_TAGS (post "yim"))))
  (PREG_REPLACE "\\r|\\n" "" (TRIM (STRIP_TAGS (post "url"))))
  (and (PREG_REPLACE "\\r|\\n" "" (TRIM (STRIP_TAGS (post "email"))))
       (and (isset (post "email")) (not (empty (post "email"))))
       (and (isset (post "email")) (!= (strpos (post "email") "@") false) (!= (strpos (post "email") ".") false)
	    (tobool (preg_match "~^(([_a-z0-9-]+)(\\.[_a-z0-9-]+)*@([a-z0-9-]+)(\\.[a-z0-9-]+)*(\\.[a-z]{2,}))$~i" 
				(post "email")))))
  (and (is_scalar (post "allow_msgform")) (preg_match "/^(\+|-)?[0-9]+$/" (post "allow_msgform")))
  (and (is_scalar (post "notify")) (preg_match "/^(\+|-)?[0-9]+$/" (post "notify")))
  (and (is_scalar (post "showonline")) (preg_match "/^(\+|-)?[0-9]+$/" (post "showonline")))
  (PREG_REPLACE "\\r|\\n" "" (TRIM (STRIP_TAGS (post "pass1"))))
  (PREG_REPLACE "\\r|\\n" "" (TRIM (STRIP_TAGS (post "pass2"))))
))


(defun white-tests ()
'(
  (mybloggie "http://herge.sisl.rites.uic.edu/notamper/instrumented/mybloggie/admin.php?mode=add" (= (get "mode") "add") "mybloggie.db")
  (opendb "http://herge.sisl.rites.uic.edu/notamper/instrumented/OpenDb/user_admin.php?op=edit&user_id=user1" (= (post "op") "update") "opendb.db")
  (phpnuke "http://herge.sisl.rites.uic.edu/notamper/instrumented/phpnuke/modules.php?name=Your_Account&op=new_user" (= (post "op") "new_user") "phpnuke.db")
  (phpnuke2 "http://herge.sisl.rites.uic.edu/notamper/instrumented/phpnuke/modules.php?name=Private_Messages&file=index&mode=post" (= (get "name") "Private_Message") "phpnuke.db")
  (landshop "http://herge.sisl.rites.uic.edu/notamper/instrumented/landshop/admin/action/objects.php?action=new" (= (post "action") "edit") "landshop.db")
  (snipegallery "http://herge.sisl.rites.uic.edu/notamper/instrumented/snipegallery/admin/gallery/gallery.php" (= (post "action") "new") "snipegallery.db")
  (sphpblog "http://herge.sisl.rites.uic.edu/notamper/instrumented/sphpblog/setup.php" true "sphpblog.db")
  (newspro "http://herge.sisl.rites.uic.edu/notamper/instrumented/newspro/postnews.php?action=post" true "newspro.db")
  (smf "http://herge.sisl.rites.uic.edu/notamper/instrumented/smf/index.php?topic=2.0" (= (get "action") "vote") "smf.db")
  (dcpportal "http://herge.sisl.rites.uic.edu/notamper/instrumented/dcp-portal/register.php" (= (post "action") "send") "dcpportal.db" (?username))
  (phpnews "http://herge.sisl.rites.uic.edu/notamper/instrumented/phpnews/index.php?action=post" (= (get "action") "post2") "phpnews.db")
  (phpnews2 "http://herge.sisl.rites.uic.edu/notamper/instrumented/phpnews/index.php?action=modifytemp&temp=news" (= (get "action") "modifytemp2") "phpnews.db")
))

; vars holding fclients for testing
(defparameter *ss-dcpportal-fclient*
  '(AND (AND (GTE 64 (LEN ?NAME))
          (GTE 64 (LEN ?SURNAME))
          (GTE 128 (LEN ?EMAIL))
          (GTE 255 (LEN ?ADDRESS))
          (GTE 9 (LEN ?ZIP))
          (GTE 32 (LEN ?CITY))
          (GTE 64 (LEN ?COUNTRY))
          (GTE 64 (LEN ?JOB))
          (GTE 32 (LEN ?TEL))
          (GTE 255 (LEN ?SIGNATURE))
          (GTE 32 (LEN ?USERNAME))
          (GTE 32 (LEN ?PASSWORD))
          (GTE 32 (LEN ?PASSWORD2))
          (= ?ACTION "send")
          (REQUIRE ?SUBMIT)
          (OR (= ?B_MONTH "0")
              (= ?B_MONTH "1")
              (= ?B_MONTH "2")
              (= ?B_MONTH "3")
              (= ?B_MONTH "4")
              (= ?B_MONTH "5")
              (= ?B_MONTH "6")
              (= ?B_MONTH "7")
              (= ?B_MONTH "8")
              (= ?B_MONTH "9")
              (= ?B_MONTH "10")
              (= ?B_MONTH "11")
              (= ?B_MONTH "12"))
          (OR (= ?B_DAY "0")
              (= ?B_DAY "1")
              (= ?B_DAY "2")
              (= ?B_DAY "3")
              (= ?B_DAY "4")
              (= ?B_DAY "5")
              (= ?B_DAY "6")
              (= ?B_DAY "7")
              (= ?B_DAY "8")
              (= ?B_DAY "9")
              (= ?B_DAY "10")
              (= ?B_DAY "11")
              (= ?B_DAY "12")
              (= ?B_DAY "13")
              (= ?B_DAY "14")
              (= ?B_DAY "15")
              (= ?B_DAY "16")
              (= ?B_DAY "17")
              (= ?B_DAY "18")
              (= ?B_DAY "19")
              (= ?B_DAY "20")
              (= ?B_DAY "21")
              (= ?B_DAY "22")
              (= ?B_DAY "23")
              (= ?B_DAY "24")
              (= ?B_DAY "25")
              (= ?B_DAY "26")
              (= ?B_DAY "27")
              (= ?B_DAY "28")
              (= ?B_DAY "29")
              (= ?B_DAY "30")
              (= ?B_DAY "31"))
           (OR (= ?B_YEAR "0")
              (= ?B_YEAR "1911")
              (= ?B_YEAR "1912")
              (= ?B_YEAR "1913")
              (= ?B_YEAR "1914")
              (= ?B_YEAR "1915")
              (= ?B_YEAR "1916")
              (= ?B_YEAR "1917")
              (= ?B_YEAR "1918")
              (= ?B_YEAR "1919")
              (= ?B_YEAR "1920")
              (= ?B_YEAR "1921")
              (= ?B_YEAR "1922")
              (= ?B_YEAR "1923")
              (= ?B_YEAR "1924")
              (= ?B_YEAR "1925")
              (= ?B_YEAR "1926")
              (= ?B_YEAR "1927")
              (= ?B_YEAR "1928")
              (= ?B_YEAR "1929")
              (= ?B_YEAR "1930")
              (= ?B_YEAR "1931")
              (= ?B_YEAR "1932")
              (= ?B_YEAR "1933")
              (= ?B_YEAR "1934")
              (= ?B_YEAR "1935")
              (= ?B_YEAR "1936")
              (= ?B_YEAR "1937")
              (= ?B_YEAR "1938")
              (= ?B_YEAR "1939")
              (= ?B_YEAR "1940")
              (= ?B_YEAR "1941")
              (= ?B_YEAR "1942")
              (= ?B_YEAR "1943")
              (= ?B_YEAR "1944")
              (= ?B_YEAR "1945")
              (= ?B_YEAR "1946")
              (= ?B_YEAR "1947")
              (= ?B_YEAR "1948")
              (= ?B_YEAR "1949")
              (= ?B_YEAR "1950")
              (= ?B_YEAR "1951")
              (= ?B_YEAR "1952")
              (= ?B_YEAR "1953")
              (= ?B_YEAR "1954")
              (= ?B_YEAR "1955")
              (= ?B_YEAR "1956")
              (= ?B_YEAR "1957")
              (= ?B_YEAR "1958")
              (= ?B_YEAR "1959")
              (= ?B_YEAR "1960")
              (= ?B_YEAR "1961")
              (= ?B_YEAR "1962")
              (= ?B_YEAR "1963")
              (= ?B_YEAR "1964")
              (= ?B_YEAR "1965")
              (= ?B_YEAR "1966")
              (= ?B_YEAR "1967")
              (= ?B_YEAR "1968")
              (= ?B_YEAR "1969")
              (= ?B_YEAR "1970")
              (= ?B_YEAR "1971")
              (= ?B_YEAR "1972")
              (= ?B_YEAR "1973")
              (= ?B_YEAR "1974")
              (= ?B_YEAR "1975")
              (= ?B_YEAR "1976")
              (= ?B_YEAR "1977")
              (= ?B_YEAR "1978")
              (= ?B_YEAR "1979")
              (= ?B_YEAR "1980")
              (= ?B_YEAR "1981")
              (= ?B_YEAR "1982")
              (= ?B_YEAR "1983")
              (= ?B_YEAR "1984")
              (= ?B_YEAR "1985")
              (= ?B_YEAR "1986")
              (= ?B_YEAR "1987")
              (= ?B_YEAR "1988")
              (= ?B_YEAR "1989")
              (= ?B_YEAR "1990")
              (= ?B_YEAR "1991")
              (= ?B_YEAR "1992")
              (= ?B_YEAR "1993")
              (= ?B_YEAR "1994")
              (= ?B_YEAR "1995")
              (= ?B_YEAR "1996")
              (= ?B_YEAR "1997")
              (= ?B_YEAR "1998"))
          (OR (= ?SEX "1") (= ?SEX "2")))
        (AND (AND (AND (AND (AND (NOT
                               (OR
                                (= ?PASSWORD "")
                                (= ?PASSWORD2 "")))
                              (NOT
                               (OR
                                (OR
                                 (OR
                                  (OR
                                   (OR
                                    (OR (= ?SEX "") (= ?NAME ""))
                                    (= ?SURNAME ""))
                                   (= ?ADDRESS ""))
                                  (= ?CITY ""))
                                 (= ?COUNTRY ""))
                                (= ?USERNAME ""))))
                         (NOT (!= ?PASSWORD ?PASSWORD2)))
                    (NOT (IN ?USERNAME "[^0-9a-zA-Z]")))
               (NOT (IN ?PASSWORD "[^0-9a-zA-Z]")))
          (IN ?EMAIL
           "^([a-zA-Z0-9]*)@([a-zA-Z0-9]*).(com|net|org|edu|int|mil|gov|arpa|biz|aero|name|coop|info|pro|museum)$"))))

#|
(defun white-tests ()
'(
  (smf "http://herge.sisl.rites.uic.edu/notamper/instrumented/smf/index.php?topic=2.0" (= (get "action") "vote"))
  (landshop2 "http://herge.sisl.rites.uic.edu/notamper/instrumented/landshop/admin/action/login.php" (= (post "action") "edit"))
  (landshop "http://herge.sisl.rites.uic.edu/notamper/instrumented/landshop/admin/action/objects.php?action=new" (= (post "action") "edit"))
  (opendb "http://herge.sisl.rites.uic.edu/notamper/instrumented/OpenDb/user_admin.php?op=edit&user_id=user1" (= (post "op") "update"))
  (newspro "http://herge.sisl.rites.uic.edu/notamper/instrumented/newspro/postnews.php?action=post")
  (snipegallery "http://herge.sisl.rites.uic.edu/notamper/instrumented/snipegallery/admin/gallery/gallery.php" (= (post "action") "new"))
  (sphpblog "http://herge.sisl.rites.uic.edu/notamper/instrumented/sphpblog/setup.php")
  (phpnuke "http://herge.sisl.rites.uic.edu/notamper/instrumented/phpnuke/modules.php?name=Private_Messages&file=index&mode=post" (= (get "name") "Private_Messages"))
  (dcpportal "http://herge.sisl.rites.uic.edu/notamper/instrumented/dcp-portal/register.php" (= (post "action") "send"))
  (mybloggie "http://herge.sisl.rites.uic.edu/notamper/instrumented/mybloggie/admin.php?mode=add" (= (get "mode") "add"))
  (phpnews "http://herge.sisl.rites.uic.edu/notamper/instrumented/phpnews/index.php?action=modifytemp&temp=news" (= (get "action") "modifytemp2"))
  ))
|#

(defun complexity (p)
  (cond ((atom p) 1)
	((find (car p) '(and or not <= => <=>)) (1+ (reduce #'+ (mapcar #'complexity (cdr p)))))
	((find (car p) '(forall exists)) (1+ (complexity (third p))))
	(t 1)))

#|
Notes on inputs.
- Don't surround regexps with //.
- double escape in regexps, e.g. \\w.
- What do we do with arrays?
- Use (var "myString") for variables--preserves case
- Make sure to type things correctly.  Can't use (type ?x "[0-9]+") and (= ?x 1)
- So if we're typing ?x with regexp, all constraints need to treat ?x as a string.
|#

;(with-open-file (f "~/working/out/ss/allresults" :direction :output :if-exists :supersede :if-does-not-exist :create) (mapc #'(lambda (x) (ssn x :numgood 2 :stream f)) '(form1 form2 form3 form4 form5 form6 form7 form8 form9 form10 form11 form12 form13 form14 form15 form16 form17 form18 form19)))

(defun ss-deftests ()
(list

 (make-ss-prob :name 'reg0 :phi '(and (= ?x ?y) (in ?x (reg "[a-d]")) (notin ?x (reg "[bc]")))
	       :types '(type (in ?x (reg "[a-z]")) (in ?y (reg "[a-z]"))))
 (make-ss-prob :name 'reg1 :phi '(and (= ?x ?y) (in ?x (reg "[a-d]")) (notin ?x (reg "[bc]")))
	       :types '(type (in ?x (reg "[a-z]")) (in ?y (reg "[a-z]")))
	       :unique '(?x ?y))
 (make-ss-prob :name 'reg2 :phi '(and (= ?x ?y) (in ?x (reg "[a-z]")) (notin ?x (reg "[f-t]")))
	       :types '(type (in ?x (reg "[a-z]")) (in ?y (reg "[a-z]")))
	       :unique '(?x ?y)
	       :variantstatus '((5 :inconsistent)))
 (make-ss-prob :name 'reg3 :phi '(and (= ?x ?y) (notin ?x (reg "[f-t]")))
	       :types '(type (in ?x (reg "[a-z]")) (in ?y (reg "[a-z]")))
	       :unique '(?x ?y))
 (make-ss-prob :name 'reg4 :phi '(and (in ?email (reg "^[\\w\\.=-]+@[\\w\\.-]+\\.[\\w\\.-]{2,4}$")) (in ?softlic1 (reg "(^-?\\d\\d*\\.\\d*$)|(^-?\\d\\d*$)|(^-?\\.\\d\\d*$)")) (in ?softlic2 (reg "(^-?\\d\\d*\\.\\d*$)")) (in ?softlic3 (reg "(^-?\\d\\d*$)")) (in ?softlic4 (reg "(^-?\\.\\d\\d*$)"))))

 (make-ss-prob :name 'range1 :phi '(and (= ?x ?y) (gte (len ?x) 5) (lte (len ?x) 15) (in ?x (reg "^[\\w\\.=-]+@[\\w\\.-]+\\.[\\w\\.-]{2,4}$")) (= (len ?y) 9) (in ?y (reg "^[\\w\\.=-]+@[\\w\\.-]+\\.[\\w\\.-]{2,4}$")) (= 1 (len ?z)) (in ?z (reg "[a,b,c]")) (in ?w (reg "[a,b,c]")) (!= ?z ?w) (lt ?t (len ?x)) (gt ?t 17) (lte ?t 21) (= ?u ?t) (= ?v false)) 
	       :types '(type (in ?x (reg "[a-z]*")) (in ?y (reg "[a-z]*")))
	       :status :inconsistent)

 (make-ss-prob :name 'toy1 :phi '(and (lt (len ?name) 50) (gte (len ?name) 5) (!= ?oldpwd "") (= ?tile "") (!= ?pwd1 "") (!= ?pwd2 "") (= ?pwd1 ?pwd2) (!= ?oldpwd ?pwd1) (in ?opt1 (reg "[a-d]")) (in ?opt2 (reg "[1-4]"))))
 (make-ss-prob :name 'toy2 :phi '(and (in ?b (reg "[0-1]")) (in ?p (reg "[0-1]")) (in ?r (reg "[0-1]")) (in ?l (reg "[0-1]")) (or (and (!= ?x "") (= ?b "0")) 	(and (!= ?x "") (= ?b "1") (= ?p "1"))	(and (!= ?x "") (= ?b "1") (= ?p "0") (= ?r "1")) (and (!= ?x "") (= ?b "1") (= ?p "0") (= ?r "0") (= ?l "1")))) 
	       :required '(?x ?b ?p ?r ?l) :unique '(?x))

 (make-ss-prob :name 'form1 :metafields '((method "POST") (url "http://localhost/notamper/smf/smf/index.php?action=pm;sa=send2"))
    :phi '(AND
        (LTE (len ?subject) 50)
        (= ?sc "704e01bb810c192d4dba4541aa99f582")
        (= ?seqnum "2353302")
        (= ?replied_to "0")
        (= ?f "inbox")
        (= ?l "-1"))
    :types `(types
        (IN ?to ,*strreg1*)
        (IN ?bcc ,*strreg1*)
        (IN ?subject ,*strreg1*)
        (IN ?message ,*strreg1*)
        (IN ?sc ,*strreg1*)
        (IN ?seqnum "/[0-9]+/")
        (IN ?replied_to "/[0-9]+/")
        (IN ?f ,*strreg1*)
        (IN ?l ,*strreg1*)))

 (make-ss-prob :name 'form2 :metafields '((method "post") (url "http://localhost/notamper/smf/smf/index.php?action=ban;sa=edit") (comment "SMF-2 : server accepts a ban without mandatory field ban_name (exploit)"))
 :variantstatus '((19 :inconsistent) (20 :inconsistent) (21 :inconsistent))
 ;:unique '(?ban_name)
 :phi '(AND
    (AND
     (IN ?expiration "never|one_day|expired")
     (IN ?full_ban "[01]")
     (IN ?cannot_post "[01]")
     (IN ?cannot_register "[01]")
     (IN ?cannot_login "[01]")
     (IN ?ban_suggestion[0] "main_ip")
     (IN ?ban_suggestion[1] "hostname")
     (IN ?ban_suggestion[2] "email")
     (IN ?ban_suggestion[3] "user")
     (= ?add_ban "Add")
     (= ?expiration "never"))
    (OR 
     (AND (!= ?ban_name "") (NOT (= ?full_ban "0")))
     (AND (!= ?ban_name "") (= ?full_ban "0") (= ?cannot_post "1"))
     (AND (!= ?ban_name "") (= ?full_ban "0") (NOT (= ?cannot_post "1")) (= ?cannot_register "1"))
     (AND (!= ?ban_name "") (= ?full_ban "0") (NOT (= ?cannot_post "1")) (NOT (= ?cannot_register "1")) (= ?cannot_login "1"))))

 :types `(types   ; removed below since
    ;(in ?sc ,*strreg1*)    ; added manually as a required variable
    ;(IN ?ban_name ,*strreg*)
    ;(IN ?expiration ,*strreg1*)    
    (IN ?full_ban "/[0-9]+/")
    (IN ?cannot_post "/[0-9]+/")
    (IN ?cannot_register "/[0-9]+/")
    (IN ?cannot_login "/[0-9]+/")
    ;(IN ?ban_suggestion[0] ,*strreg*)
    ;(IN ?ban_suggestion[1] ,*strreg*)
    ;(IN ?ban_suggestion[2] ,*strreg*)
    ;(IN ?ban_suggestion[3] ,*strreg*)
    ;(IN ?add_ban ,*strreg1*)
    (IN ?expire_date "/[0-9]+/")
    ;(IN ?reason ,*strreg1*)
    ;(IN ?notes ,*strreg1*)
    ;(IN ?main_ip ,*strreg1*)
    ;(IN ?hostname ,*strreg1*)
    ;(IN ?email ,*strreg1*)
    ;(IN ?user ,*strreg1*)))  
))


 (make-ss-prob :name 'form3 :metafields '((method "post") (url "http://localhost/ezybiz/ezybiz/gencompanyadd.php") (comment "EZYBIZ-1 : server truncates longer company name (false positive) 
EZYBIZ-2 : server accepts data without mandatory field email (exploit)"))
  :variantstatus `((24 :inconsistent))
  :phi '(AND    
    (lte (len ?name) 50)
    (lte (len ?address1) 100)
    (lte (len ?address2) 100)
    (lte (len ?city) 50)    
    (lte (len ?state) 20)    
    (lte (len ?zip) 15)    
    (lte (len ?country) 20)    
    (lte (len ?phone1) 20)    
    (lte (len ?phone2) 20)    
    (lte (len ?phone3) 20)    
    (lte (len ?phone4) 20)    
    (lte (len ?email1) 50)    
    (lte (len ?web) 100)    
    (= ?nonprintable 1)
    (NOT (= ?name ""))
    (NOT (= ?address1 ""))
    (NOT (= ?city ""))
    (NOT (= ?state ""))
    (NOT (= ?zip ""))
    (IN ?zip "/[0-9]*/")                            
    (OR (= (len ?zip) 5) (= (len ?zip) 9))        
    (NOT (= ?country ""))
    (NOT (= ?phone1 ""))
    (= (len ?phone1) 10)                                          
    (NOT (= ?phone4 ""))
    (= (len ?phone4) 10)
    (NOT (= ?email1 ""))
    (IN ?email1 "/^.+@.+\\..{2,3}$/")
    (NOT (contains ?email1 ">"))                            
    (NOT (contains ?email1 "\("))
    (NOT (contains ?email1 "\)"))
    (NOT (contains ?email1 "<"))
    (NOT (contains ?email1 ">"))
    (NOT (contains ?email1 ","))
    (NOT (contains ?email1 ";"))
    (NOT (contains ?email1 ":"))
    ;(NOT (contains ?email1 "\\"))  ; parser error on Kaluza
    (NOT (contains ?email1 "\/"))
    (NOT (contains ?email1 "\""))
    (NOT (contains ?email1 "\["))
    (NOT (contains ?email1 "\]")))
  :types `(type
    (IN ?name ,*strreg*)
    (IN ?address1 ,*strreg*)
    (IN ?address2 ,*strreg*)
    (IN ?city ,*strreg*)
    (IN ?state ,*strreg*)
    (IN ?zip "/[0-9]*/")
    (IN ?country ,*strreg*)
    (IN ?phone1 "/[0-9]*/")
    (IN ?phone2 "/[0-9]*/")
    (IN ?phone3 "/[0-9]*/")
    (IN ?phone4 "/[0-9]*/")
    (IN ?email1 ,*strreg*)
    (IN ?web ,*strreg*)))
    ;(IN ?nonprintable ,*strreg*)))

(make-ss-prob :name 'form4 :metafields '((method "post") (url "http://localhost/ezybiz/ezybiz/gljourupd.php")
	      (comment "Update voucher and bypass maxlength restriction on description (exploit)"))
 :phi '(AND
    (= ?vouchername "a")
    (= ?voucherdescription "describe this")
    (lte (len ?voucherdescription) 30)
    (= ?voucherentrydate "2010-01-10")
    (= ?updatev "1")
    (= ?vid 1)
    (= ?voucherid 1)
    (= ?lastchangedate "2010-01-20 21:35:04"))

 :types `(type
    (IN ?vouchername ,*strreg1*)
    (IN ?voucherdescription ,*strreg1*)
    (IN ?voucherentrydate "/[0-9\-:]+/")
    (IN ?updatev ,*strreg1*)
    (IN ?vid "/[0-9]+/")
    (IN ?voucherid "/[0-9]+/")
    (IN ?lastchangedate "/[0-9\\-: ]+/")))

(make-ss-prob :name 'form5 :metafields '((method "post") (url "http://localhost/ezybiz/ezybiz/glacctadd.php")
	      (comment "EZYBIZ-4 : Add accnt bypassing maxlength restrictions on name and description of accnt."))
 :phi '(AND
    (= ?accounttypeid 1) 
    (= ?nonprintable 1)
    (lte (len ?name) 6)
    (lte (len ?description) 30)
    (IN ?isheader "[01]")
    (= ?isheader 0)
    (IN ?header "/(0|2|41|3|5|42|43|44|4|9|45|46|47|10|6|7|8|48|49|50|51|52|53|54|55|56|57|58|59|60)/")
    (= ?header 0))
 :types `(type
    (IN ?accounttypeid "/[0-9]+/") 
    (IN ?nonprintable "/[0-9]+/")
    (IN ?name ,*strreg1*)
    (IN ?description ,*strreg1*)
    (IN ?isheader "/[0-9]+/")
    (IN ?header "/[0-9]+/")))

(make-ss-prob :name 'form6 :metafields '((method "post") (url "http://98.130.249.57/smf/index.php?action=profile2") '   (multipart t) (comment "SMF-3 : bypass length limitation of 50 on the personal text on the profile page "))
 ;:unique '(?personaltext ?bday3 ?bday1 ?bday2 ?aim ?yim ?replied_to ?icq ?msn?signature ?websitetitle ?websiteurl)
	     
 :phi '(and 
        (lte (len (var "personalText")) 50)
        (lte (len ?bday3) 4)
        (lte (len ?bday1) 2)
        (lte (len ?bday2) 2)
        (lte (len (var "AIM")) 16)
        (lte (len (var "YIM")) 32)
        (= ?sc "f78b5621d8c08b521cb61f2073a854fe")
        (= (var "userID") "1")
        (= ?sa "forumProfile")
        (in ?avatar_choice "server_stored|external|upload")
        (in ?cat "blank.gif|Actors/|Musicians/")
        (in ?file "/null/")
        (in ?gender "/0|1|2/")
        (= ?avatar_choice "server_stored")
        (= ?cat "blank.gif"))

 :types '(types 
        (IN ?avatar_choice "/[a-zA-Z_/]+/")
        (IN ?cat "/[a-zA-Z\\./]+/")
        (IN ?file "/[a-zA-Z/]+/")
        (IN (var "personalText") "/[a-zA-Z]+/")
        (IN ?bday1 "/[0-9]+/")
        (IN ?bday2 "/[0-9]+/")
        (IN ?bday3 "/[0-9]+/")
        (IN ?seqnum "/[0-9]+/")
        (IN ?replied_to "/[0-9]+/")
        (IN (var "AIM") "/[a-zA-Z]+/")
        (IN (var "YIM") "/[a-zA-Z]+/")
        (IN (var "ICQ") "/[a-zA-Z]+/")
        (IN (var "MSN") "/[a-zA-Z]+/")
        (IN ?signature "/[a-zA-Z]+/")
        (IN (var "websiteTitle") "/[a-zA-Z]+/")
        (IN (var "websiteUrl") "/[a-zA-Z]+/")
        (IN ?sc "/[a-zA-Z0-9]+/")
        (IN (var "userID") "/[0-9]+/")
        (IN ?sa "/[a-zA-Z]+/")))

(make-ss-prob :name 'form7 :metafields '((method "post") (url "http://98.130.249.57/smf/index.php?action=post2;start=0;board=1") (multipart t)
	      (comment "SMF-4 : bypass length limitation of 80 on the subject field of a new thread"))
 :phi '(and 
    (= ?topic 0)
    (lte (len ?subject) 80)
    (= ?notify 0)
    (= ?lock 0)
    (= ?sticky 0)
    (= ?move 0)
    (= ?additional_options 0)
    (= ?sc "bb91d847c90ac3dbd5ee60366a7f41c4")
    (= ?seqnum 29828)
    (in ?notify "/0|1/")
    (in ?lock "/0|1/")
    (in ?goback "/1/")
    (in ?sticky "/0|1/")
    (in ?ns "/NS/")
    (in ?move "/0|1/")
    (in ?announce_topic "/1/")
    (in ?icon "/xx|thumbup|thumbdown|exclamation|question|lamp|smiley|angry|cheesy|grin|sad|wink/")
    (= ?icon "xx"))

 :types '(types
    (IN ?topic "/[0-9]+/")
    (IN ?subject "/[a-zA-Z]+/")    
    (IN ?notify "/[0-9]+/")
    (IN ?lock "/[0-9]+/")
    (IN ?sticky "/[0-9]+/")
    (IN ?move "/[0-9]+/")
    (IN ?additional_options "/[0-9]+/")
    (IN ?sc "/[a-zA-Z0-9]+/")
    (IN ?seq_num "/[0-9]+/")
    (IN ?notify "/[0-9]+/")
    (IN ?sticky "/[0-9]+/")
    (IN ?lock "/[0-9]+/")
    (IN ?goback "/[0-9]+/")
    (IN ?ns "/[a-zA-Z]+/")
    (IN ?move "/[0-9]+/")
    (IN ?announce_topic "/[0-9]+/")))

(make-ss-prob :name 'form8 :metafields '((method "post") (url "http://98.130.249.57/smf/index.php?action=vote;topic=2.0;poll=1")
	      (comment "SMF-5 : submission of invalid option in a poll is accepted and counted as a vote"))
 :phi '(and 
(= ?sc "bb91d847c90ac3dbd5ee60366a7f41c4")
(in ?options[0] "/0/")
(in ?options[1] "/1/")
(in ?options[2] "/2/")
(in ?options[3] "/3/")
(in ?options[4] "/4/"))

 :types '(type
    (IN ?sc "/[a-zA-Z0-9]+/")
    (IN ?options[0] "/[0-9]+/")
    (IN ?options[1] "/[0-9]+/")
    (IN ?options[2] "/[0-9]+/")
    (IN ?options[3] "/[0-9]+/")
    (IN ?options[4] "/[0-9]+/")) )

(make-ss-prob :name 'form9 :metafields '((method "post") (url "openit/index.php?Edit=Employees&amp;ID=3")
	      (comment "modify the hidden input employee_EmployeeID to the ID of a different user to edit the first and last name in their profile"))
 :phi '(and 
    (= (var "employee_EmployeeID") "3")
    (in (var "employee_Contractor") "/1/")
    (in (var "employee_ITTechnician") "/1/")
    (in (var "KeepPassword") "/1/")
    (= (var "KeepPassword") "1")
    (in (var "employee_Department") "/0|1/")
    (= (var "employee_Department") "0")
    (in (var "employee_Campus") "/0/")
    (= (var "employee_Campus") "0")
    (in (var "employee_Language") "/en\-US|ct\-CT|de\-DE|es\-ES|fr\-CA|it\-IT|nl\-NL|pl\-PL|pt\-BR/")
    (= (var "employee_Language") "en-US"))

 :types '(type
    (IN (var "employee_EmployeeID") "/[0-9]+/")
    (IN (var "employee_Contractor") "/[0-9]+/")
    (IN (var "employee_ITTechnician") "/[0-9]+/")
    (IN (var "KeepPassword") "/[0-9]+/")
    (IN (var "employee_FirstName") "/[a-zA-Z]+/")
    (IN (var "employee_LastName") "/[a-zA-Z]+/")
    (IN (var "employee_MiddleInitial") "/[a-zA-Z]+/")
    (IN (var "employee_ClearPassword") "/[a-zA-Z]+/")
    (IN (var "KeepPassword") "/[0-9]+/")
    (IN (var "employee_Department") "/[0-9]+/")
    (IN (var "employee_Campus") "/[0-9]+/")
    (IN (var "employee_HomePhone") "/[a-zA-Z0-9]+/") 
    (IN (var "employee_WorkPhone") "/[a-zA-Z0-9]+/") 
    (IN (var "employee_MobilePhone") "/[a-zA-Z0-9]+/") 
    (IN (var "employee_Fax") "/[a-zA-Z0-9]+/") 
    (IN (var "employee_EmailAddress") "/[a-zA-Z]+/")
    (IN (var "employee_JabberAccount") "/[a-zA-Z0-9]+/") 
    (IN (var "employee_HomeStreetAddress") "/[a-zA-Z0-9]+/") 
    (IN (var "employee_HomePOBox") "/[a-zA-Z0-9]+/") 
    (IN (var "employee_HomeCity") "/[a-zA-Z0-9]+/") 
    (IN (var "employee_HomeState") "/[a-zA-Z0-9]+/") 
    (IN (var "employee_HomeZip") "/[a-zA-Z0-9]+/") 
    (IN (var "employee_Language") "/[a-zA-Z\\-]+/") 
    (IN (var "employee_Notes") "/[a-zA-Z0-9]+/") ))

(make-ss-prob :name 'form10 :metafields '((method "post") (url "OpenDb/user_admin.php")
	      (comment "server accepts an option that is outside of the options range"))
 :phi '(and 
    (= ?user_id "user1")
    (lte (len ?fullname) 100)
    (lte (len ?email_addr) 100)
    (lte (len ?snail[addr_line_1]) 255)
    (= ?snail[addr_line_1] "address") 
    (lte (len ?snail[addr_line_2]) 255)
    (= ?snail[addr_line_2] "address2") 
    (lte (len ?snail[city_3]) 100)
    (= ?snail[city_3] "city") 
    (lte (len ?snail[state_4]) 100)
    (= ?snail[state_4] "state") 
    (lte (len ?snail[postcode_5]) 10)
    (= ?postcode_5 "90210")
    (lte (len ?snail[phone_no_10]) 50)
    (lte (len ?snail[phone_no_11]) 50)
    (lte (len ?snail[phone_no_12]) 50)
    (= ?op "update")
    (in ?snail[public_address_ind] "/Y/")
    (= ?snail[public_address_ind] "Y")
    (in ?snail[borrow_address_ind] "/Y/")
    (in ?user_role "/ADMINISTRATOR|BORROWER|GUEST|OWNER/")
    (= ?user_role "BORROWER")
    (in ?uid_theme "/default/")
    (= ?uid_theme "default")
    (in ?snail[country_6] "/AF|AL|DZ|AS|AD|AO|AI|AQ|AG|AR|AM|AW|AU|AT|AZ|BS|BH|BD|BB|BY|BE|BZ|BJ|BM|BT|BO|BA|BW|BV|BR|IO|BN|BG|BF|BI|KH|CM|CA|CV|KY|CF|TD|CL|CN|CX|CC|CO|KM|CG|CD|CK|CR|CI|HR|CU|CY|CZ|DK|DJ|DM|DO|TP|EC|EG|SV|GQ|ER|EE|ET|FK|FO|FJ|FI|FR|FX|GF|PF|TF|GA|GM|GE|DE|GH|GI|GR|GL|GD|GP|GU|GT|GN|GW|GY|HT|HM|VA|HN|HK|HU|IS|IN|ID|IR|IQ|IE|IL|IT|JM|JP|JO|KZ|KE|KI|KP|KR|KW|KG|LA|LV|LB|LS|LR|LY|LI|LT|LU|MO|MK|MG|MW|MY|MV|ML|MT|MH|MQ|MR|MU|YT|MX|FM|MD|MC|MN|MS|MA|MZ|MM|NA|NR|NP|NL|AN|NC|NZ|NI|NE|NG|NU|NF|MP|NO|OM|PK|PW|PS|PA|PG|PY|PE|PH|PN|PL|PT|PR|QA|RE|RO|RU|RW|KN|LC|VC|WS|SM|ST|SA|SN|SC|SL|SG|SK|SI|SB|SO|ZA|GS|ES|LK|SH|PM|SD|SR|SJ|SZ|SE|CH|SY|TW|TJ|TZ|TH|TG|TK|TO|TT|TN|TR|TM|TC|TV|UG|UA|AE|GB|US|UM|UY|UZ|VU|VE|VN|VG|VI|WF|EH|YE|YU|ZM|ZW|somenonexistantcountry/")
    (= ?snail[country_6] "somenonexistantcountry")    
    (= ?fullname "name surname")
    (= ?email_addr "nskrou2@uic.edu"))
 :types '(type
    (IN ?user_id "/[a-zA-Z0-9]+/")
    (IN ?email_addr "/[@a-zA-Z0-9\\.]+/") 
    (IN ?fullname "/[a-zA-Z ]+/") 
    (IN ?user_role "/[A-Z]+/") 
    (IN ?uid_theme "/[a-zA-Z0-9]+/") 
    (IN ?snail[country_6] "/[a-zA-Z]+/") 
    (IN ?snail[addr_line_1] "/[a-zA-Z0-9]+/") 
    (IN ?snail[addr_line_2] "/[a-zA-Z0-9]+/") 
    (IN ?snail[city_3] "/[a-zA-Z0-9]+/") 
    (IN ?snail[state_4] "/[a-zA-Z0-9]+/") 
    (IN ?postcode_5 "/[0-9]+/") 
    (IN ?snail[phone_no_10] "/[0-9\\-\\+]+/") 
    (IN ?snail[phone_no_11] "/[0-9\\-\\+]+/") 
    (IN ?snail[phone_no_12] "/[0-9\\-\\+]+/") 
    (IN ?op "/[a-zA-Z]+/") 
    (IN ?snail[public_address_ind] "/[a-zA-Z0-9]+/")) )

(make-ss-prob :name 'form11 :metafields '((method "post") (url "mybloggie/admin.php?mode=add")
	      (comment "(1) bypasses javascript checks that subject and message length are > 2 and (2) submit a menu option that is not present in the range of values for category"))

 :phi '(and 
	 (lte (len ?subject) 60)
	 (lte (len ?helpbox) 100)
	 (= ?helpbox "Tip: Apply style to the selected text")
	 (lte (len ?dd) 2)
	 (= ?dd "27")
	 (lte (len ?yy) 5)
	 (= ?yy "2010")
	 (lte (len ?hh) 2)
	 (= ?hh "05")
	 (lte (len ?min) 2)
	 (= ?min "34")
	 (lte (len ?sec) 2)
	 (= ?sec "43")
	 (in ?edit_date "/1/")
	 (in ?category "/1/")
	 (in ?mm "/1|2|3|4|5|6|7|8|9|10|11|12/")
 	 (= ?mm "1")
 	 (NOT (lt (len ?subject) 2))
 	 (NOT (lt (len ?message) 2))
	 (= ?submit "Submit"))  ; added manually

 :types `(type 
	 (IN ?subject "/[a-zA-Z]+/")
	 (IN ?helpbox "/[a-zA-Z \:]+/")
	 (IN ?edit_date "/[1]+/")
	 (IN ?dd "/[\\-xX0-9a-f]+/")
	 (IN ?yy "/[\\-xX0-9a-f]+/")
	 (IN ?hh "/[\\-xX0-9a-f]+/")
	 (IN ?min "/[\\-xX0-9a-f]+/")
	 (IN ?sec "/[\\-xX0-9a-f]+/")
	 (IN ?trackback_url "/[a-zA-Z]+/")
	 (IN ?edit_date "/[1]+/")
	 (IN ?category "/[1]+/")
	 (IN ?mm "/[0123456789]+/")
	 (IN ?message "/[a-zA-Z]+/")
	 (in ?submit ,*strreg1*) ))   ; added manually

; problem: when solving bad (not (= ?redirect_to ...)), hampi not finding answer
;   and it's taking a really long time for each string length
; solution: set *ss-max-length* to 10
(make-ss-prob :name 'form12 :metafields '((method "post") (url "b2evolution/admin.php")
	      (comment "bypasses maxlength=255 on post_title input"))
 :phi '(and 
	 (lte (len ?post_title) 255)
	 (= ?set_issue_date "now")
	 (= ?item_issue_date "01/21/10")
	 (lte (len ?item_issue_time) 10)
	 (= ?item_issue_time "14:55:48")
	 (lte (len ?item_tags) 255)
	 (= ?post_category 1)
	 (= ?post_status "draft")
	 (= ?post_comment_status "open")
	 (= ?ctrl "items")
	 (= ?blog "1")
	 (= ?mode "")
	 (= (var "post_ID") "0")
	 (= ?redirect_to "http://98.130.249.57/b2evolution/admin.php?ctrl=items&filter=restore&blog=1")
	 (= ?preview "1")
	 (= ?more "1")
	 (= ?preview_userid "1")
	 (= ?post_locale "en-US")
	 (= (var "item_typ_ID") "1")
	 (= ?post_url "")
	 (= ?post_excerpt "")
	 (= ?post_urltitle "")
	 (= ?titletag "")
	 (= ?metadesc "")
	 (= ?metakeywords "")
	 (= ?trackback_url "")
	 (= ?renderers_displayed "1")
	 (= ?renderers[0] "b2evSmil")
	 (= ?renderers[1] "b2evALnk")
	 (= ?renderers[2] "evo_videoplug")
	 (= ?renderers[3] "b2WPAutP")
	 (= ?item_featured "0")
	 (= ?item_order "")
	 (= ?item_double1 "")
	 (= ?item_double2 "")
	 (= ?item_double3 "")
	 (= ?item_double4 "")
	 (= ?item_double5 "")
	 (= ?item_varchar1 "")
	 (= ?item_varchar2 "")
	 (= ?item_varchar3 "")
	 (in ?set_issue_date "/now|set/")
	 (in ?post_category "/1/")
	 (in ?post_extracats[0] "/1/")
	 (in ?post_status "/published|protected|private|draft|deprecated|redirected/")
	 (in ?post_comment_status "/open|closed|disabled/"))

 :types `(type 
	 (IN ?post_title "/[a-zA-Z]+/")
	 (IN ?item_issue_date "/[/012]+/")
	 (IN ?item_issue_time "/[1458:]+/")
	 (IN ?item_tags "/[a-zA-Z]+/")
	 (IN ?ctrl "/[eimst]+/" )
	 (IN ?blog "/[\\-xX0-9a-f]*/" )
	 (IN ?mode "/[a-zA-Z]*/" )
	 (IN (var "post_ID") "/[\\-xX0-9a-f]+/" )
	 (IN ?redirect_to ,*strreg1*)  ;"/[&\\.\\/012345789\\:;\\=\\?abcdefghilmnoprstuv]+/" )
	 (IN ?preview "/[\\-xX0-9a-f]+/" )
	 (IN ?more "/[\\-xX0-9a-f]+/" )
	 (IN ?preview_userid "/[\\-xX0-9a-f]+/" )
	 (IN ?post_locale "/[-SUen]+/" )
	 (IN (var "item_typ_ID") "/[\\-xX0-9a-f]+/" )
	 (IN ?post_url "/[a-zA-Z]*/" )
	 (IN ?post_excerpt "/[a-zA-Z]*/" )
	 (IN ?post_urltitle "/[a-zA-Z]*/" )
	 (IN ?titletag "/[a-zA-Z]*/" )
	 (IN ?metadesc "/[a-zA-Z]*/" )
	 (IN ?metakeywords "/[a-zA-Z]*/" )
	 (IN ?trackback_url "/[a-zA-Z]*/" )
	 (IN ?renderers_displayed "/[\\-xX0-9a-f]+/" )
	 (IN ?renderers[0] "/[2Sbeilmv]+/" )
	 (IN ?renderers[1] "/[2ALbeknv]+/" )
	 (IN ?renderers[2] "/[_degilopuv]+/" )
	 (IN ?renderers[3] "/[2APWbtu]+/" )
	 (IN ?item_featured "/[\\-xX0-9a-f]+/" )
	 (IN ?item_order "/[a-zA-Z]*/" )
	 (IN ?item_double1 "/[a-zA-Z]*/" )
	 (IN ?item_double2 "/[a-zA-Z]*/" )
	 (IN ?item_double3 "/[a-zA-Z]*/" )
	 (IN ?item_double4 "/[a-zA-Z]*/" )
	 (IN ?item_double5 "/[a-zA-Z]*/" )
	 (IN ?item_varchar1 "/[a-zA-Z]*/" )
	 (IN ?item_varchar2 "/[a-zA-Z]*/" )
	 (IN ?item_varchar3 "/[a-zA-Z]*/" )
	 (IN ?set_issue_date "/[enostw]+/")
	 (IN ?post_category "/[1]+/")
	 (IN ?post_extracats[0] "/[1]+/")
	 (IN ?post_status "/[abcdefhiloprstuv]+/")
	 (IN ?post_comment_status "/[abcdeilnops]+/")
	 (IN ?content "/[a-zA-Z]+/")))

(make-ss-prob :name 'form13 :metafields '((method "post") (url "phpnuke/modules.php?name=Your_Account")
	      (comment "bypasses maxlength=255 on user_email input"))
 :phi '(and 
	 (lte (len ?username) 25)
	 (lte (len ?user_email) 255)
	 (lte (len ?user_password) 40)
	 (lte (len ?user_password2) 40)
	 (= ?op "new user"))
 :types '(type 
	 (IN ?username "/[a-zA-Z]+/")
	 (IN ?user_email "/[a-zA-Z]+/")
	 (IN ?user_password "/[a-zA-Z]+/")
	 (IN ?user_password2 "/[a-zA-Z]+/")
	 (IN ?op "/[ enrsuw]+/" )) )

(make-ss-prob :name 'form14 :metafields '((method "post") (url "OpenIT/index.php?Edit=Groups&amp;ID=3")
	  (comment "By pass HTML restrictions on edit group page to force application to an inconsistent state. "))
 :phi '(and 
	 (= (var "group_GroupID") "3")
	 (= (var "group_Name") "testme")
	 (= (var "group_ComputersPerm") "0")
	 (= (var "group_PeripheralsPerm") "0")
	 (= (var "group_SoftwarePerm") "0")
	 (= (var "group_EmployeesPerm") "0")
	 (= (var "group_OutOfOfficePerm") "0")
	 (= (var "group_ReportsPerm") "0")
	 (= (var "group_SupportPerm") "0")
	 (= (var "group_KBPerm") "0")
	 (= (var "group_PolicyPerm") "0")
	 (= (var "group_GroupPerm") "0")
	 (= (var "group_LookupsPerm") "0")
	 (= (var "group_NewsPerm") "0")
	 (in (var "group_ComputersPerm") "/0|1|2|3|4/")
	 (in (var "group_PeripheralsPerm") "/0|1|2|3|4/")
	 (in (var "group_SoftwarePerm") "/0|1|2|3|4/")
	 (in (var "group_EmployeesPerm") "/0|1|2|3|4/")
	 (in (var "group_OutOfOfficePerm") "/0|1|2|3|4/")
	 (in (var "group_ReportsPerm") "/0|1|2|3|4/")
	 (in (var "group_SupportPerm") "/0|1|2|3|4/")
	 (in (var "group_KBPerm") "/0|1|2|3|4/")
	 (in (var "group_PolicyPerm") "/0|1|2|3|4/")
	 (in (var "group_GroupPerm") "/0|1|2|3|4/")
	 (in (var "group_LookupsPerm") "/0|1|2|3|4/")
	 (in (var "group_NewsPerm") "/0|1|2|3|4/")
	 (NOT (= (var "group_Name") "")))
 :types '(type 
	 (in (var "group_GroupID") "/[\\-xX0-9a-f]+/")
	 (in (var "group_Name") "/[emst]*/")
	 (in (var "group_ComputersPerm") "/[01234]+/")
	 (in (var "group_PeripheralsPerm") "/[01234]+/")
	 (in (var "group_SoftwarePerm") "/[01234]+/")
	 (in (var "group_EmployeesPerm") "/[01234]+/")
	 (in (var "group_OutOfOfficePerm") "/[01234]+/")
	 (in (var "group_ReportsPerm") "/[01234]+/")
	 (in (var "group_SupportPerm") "/[01234]+/")
	 (in (var "group_KBPerm") "/[01234]+/")
	 (in (var "group_PolicyPerm") "/[01234]+/")
	 (in (var "group_GroupPerm") "/[01234]+/")
	 (in (var "group_LookupsPerm") "/[01234]+/")
	 (in (var "group_NewsPerm") "/[01234]+/")))

(make-ss-prob :name 'form15 :metafields '((method "") (url "OpenIT/index.php?Edit=Software&amp;ID=3")
	      (comment "By pass this restriction to create entries without titles. "))
 :variantstatus '((3 :inconsistent) (15 :inconsistent) (17 :contingent) (16 :inconsistent))
 :phi '(and 
	 (= (var "software_ID") "3")
	 (= (var "software_Title") "testme")
	 (= (var "software_Licenses") "0")
	 (= (var "software_Vendor") "0")
	 (= (var "software_ManufacturedDate[M]") "1")
	 (= (var "software_ManufacturedDate[Y]") "1990")
	 (in (var "software_isOS") "/1/")
	 (in (var "software_Vendor") "/0/")
	 (in (var "software_ManufacturedDate[M]") "/1|2|3|4|5|6|7|8|9|10|11|12/")
	 (in (var "software_ManufacturedDate[Y]") "/1990|1991|1992|1993|1994|1995|1996|1997|1998|1999|2000|2001|2002|2003|2004|2005|2006|2007|2008|2009|2010/")
	 (NOT (= (var "software_Title") ""))
	 (OR (= (var "software_Licenses") "") (AND (NOT (= (var "software_Licenses") "")) (IN (var "software_Licenses") "/(^-?\\d\\d*\\.\\d*$)|(^-?\\d\\d*$)|(^-?\\.\\d\\d*$)/")) ))
 :types '(type 
	 (IN (var "software_ID") "/[\\-xX0-9a-f]+/" )
	 (IN (var "software_Title") "/[emst]*/")
	 (IN (var "software_Version") "/[a-zA-Z]+/")
	 (IN (var "software_Licenses") "/[\\-xX0-9a-f]*/")
	 (IN (var "software_isOS") "/[1]+/")
	 (IN (var "software_Vendor") "/[0]+/")
	 (IN (var "software_ManufacturedDate[M]") "/[0123456789]+/")
	 (IN (var "software_ManufacturedDate[Y]") "/[0123456789]+/")) )

(make-ss-prob :name 'form16 :metafields '((method "post") (url "legalcase/upd_exp.php")
	      (comment "Expense report menu does not work after entering an expense report with an unknown type of expense report (good example of app becoming unstable)"))
 :phi '(and 
	 (= ?id_case "0")
	 (= ?cost "0")
	 (= ?type "_exptypes01")
	 (in ?type "/_exptypes01|_exptypes02|_exptypes_other/"))
 :types '(type 
	 (IN ?id_case "/[\\-xX0-9a-f]+/" )
	 (IN ?cost "/[\\-xX0-9a-f]+/")
	 (IN ?type "/[012_ehoprstxy]+/")
	 (IN ?description "/[a-zA-Z]+/")
 	 (IN ?comment "/[a-zA-Z]+/")))

(make-ss-prob :name 'form17 :metafields '((method "post") (url "legalcase/upd_app.php")
	      (comment "Expense report menu does not work after entering an expense report with an unknown type of expence report (good example of app becoming unstable)"))
 :phi '(and 
	 (= ?start_day "30")
	 (= ?start_year "2010")
	 (= ?delta_days "0")
	 (= ?delta_minutes "0")
	 (= ?title "New activity")
	 (= ?id_app "0")
	 (= ?id_case "0")
	 (= ?id_followup "0")
	 (= ?start_month "1")
	 (= ?start_hour "23")
	 (= ?start_minutes "55")
	 (= ?type "meeting")
	 (= ?author "0")
	 (= ?client "0")
	 (in ?start_month "/1|2|3|4|5|6|7|8|9|10|11|12/")
	 (in ?start_hour "/00|01|02|03|04|05|06|07|08|09|10|11|12|13|14|15|16|17|18|19|20|21|22|23/")
	 (in ?start_minutes "/00|05|10|15|20|25|30|35|40|45|50|55/")
	 (in ?type "/court_session|meeting|phone_conversation/")
	 (in ?author "/0/")
	 (in ?client "/0/"))
 :types '(type 
	 (IN ?start_day "/[\\-xX0-9a-f]+/")
	 (IN ?start_year "/[\\-xX0-9a-f]+/")
	 (IN ?delta_days "/[\\-xX0-9a-f]+/" )
	 (IN ?delta_minutes "/[\\-xX0-9a-f]+/" )
	 (IN ?title "/[ Naceitvwy]+/")
	 (IN ?id_app "/[\\-xX0-9a-f]+/" )
	 (IN ?id_case "/[\\-xX0-9a-f]+/" )
	 (IN ?id_followup "/[\\-xX0-9a-f]+/" )
	 (IN ?start_month "/[0123456789]+/")
	 (IN ?start_hour "/[0123456789]+/")
	 (IN ?start_minutes "/[012345]+/")
	 (IN ?type "/[_aceghimnoprstuv]+/")
	 (IN ?author "/[0]+/")
	 (IN ?client "/[0]+/")
	 (IN ?description "/[a-zA-Z]+/")))

(make-ss-prob :name 'form18 :metafields '((method "post") (url "https://www.smi-online.co.uk:443/users/default.asp")
	      (comment "By pass HTML restrictions on user sector."))
 :phi '(and 
	 (= ?referurl "")
	 (= (var "intValStatus") "0")
	 (lte (len ?usr_title) 50)
	 (= ?usr_title "Mr")
	 (lte (len ?usr_forename) 50)
	 (= ?usr_forename "First1")
	 (lte (len ?usr_surname) 50)
	 (= ?usr_surname "Surname1")
	 (lte (len ?usr_phone) 50)
	 (= ?usr_phone "1111111111")
	 (lte (len ?usr_fax) 50)
	 (= ?usr_fax "2222222222")
	 (lte (len ?usr_email) 50)
	 (= ?usr_email "first@first.com")
	 (lte (len ?usr_jobtitle) 60)
	 (= ?usr_jobtitle "Software Engineer")
	 (lte (len ?usr_org) 100)
	 (= ?usr_org "Test Networks")
	 (lte (len ?usr_add1) 100)
	 (= ?usr_add1 "address1")
	 (lte (len ?usr_add2) 100)
	 (lte (len ?usr_add3) 100)
	 (lte (len ?usr_city) 70)
	 (= ?usr_city "city")
	 (lte (len ?usr_county) 70)
	 (= ?usr_county "OR")
	 (lte (len ?usr_postcode) 20)
	 (= ?usr_postcode "123234")
	 (lte (len ?usr_pass) 50)
	 (= ?usr_pass "")
	 (= ?usr_empsector "2")
	 (= ?usr_country "223")
	 (in ?usr_emailsubs "/1|2|3/")
	 (in ?usr_empsector "/0|0|0|2|3|4|6|8|9|10|5|11|13|12|14|15|16|18|19|20|21|22|17|23|1|24|25|26|27|28|29|30|31|32|33|34|35|36|37|38|39|40|7|0|1|0/")
	 (in ?usr_country "/0|0|0|1|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24|25|26|27|28|29|30|31|32|33|34|35|36|37|38|39|40|41|42|43|240|44|45|46|47|48|49|50|51|52|53|54|55|56|57|58|59|60|61|62|63|64|65|241|67|68|69|70|71|72|73|74|75|76|77|78|79|80|81|242|82|83|84|85|86|87|88|89|90|91|92|93|94|95|96|97|252|98|99|100|101|102|103|104|105|106|107|108|110|111|112|113|114|115|116|119|120|121|122|123|124|125|126|127|128|129|130|131|132|133|134|135|136|137|163|138|139|140|141|142|143|144|145|146|147|244|148|149|150|245|151|152|153|155|154|156|157|158|159|160|161|162|117|164|165|166|167|251|168|169|170|171|172|173|174|175|176|177|178|179|180|181|182|183|184|185|186|187|188|253|189|246|190|191|192|193|194|195|196|197|198|118|199|200|201|202|203|204|205|206|247|207|208|209|248|210|211|212|213|214|215|216|217|218|219|220|221|222|224|223|225|249|226|227|228|229|230|231|232|250|233|234|235|236|237|238|0/"))
 :types '(type 
	 (IN ?referurl "/[a-zA-Z]*/" )
	 (IN (var "intValStatus") "/[\\-xX0-9a-f]+/" )
	 (IN ?usr_title "/[Mr]+/")
	 (IN ?usr_forename "/[1First]+/")
	 (IN ?usr_surname "/[1Saemnru]+/")
	 (IN ?usr_phone "/[\\-0-9]+/")
	 (IN ?usr_fax "/[\\-0-7]+/")
	 (IN ?usr_email "/[\\.@cfimorst]+/")
	 (IN ?usr_jobtitle "/[ ESaefginortw]+/")
	 (IN ?usr_org "/[ NTekorstw]+/")
	 (IN ?usr_add1 "/[1aders]+/")
	 (IN ?usr_add2 "/[a-zA-Z]+/")
	 (IN ?usr_add3 "/[a-zA-Z]+/")
	 (IN ?usr_city "/[city]+/")
	 (IN ?usr_county "/[OR]+/")
	 (IN ?usr_postcode "/[\\-xX0-9a-f]+/")
	 (IN ?usr_pass "/[a-zA-Z]*/")
	 (IN ?usr_emailsubs "/[123]+/")
	 (IN ?usr_empsector "/[0123456789]+/")
	 (IN ?usr_country "/[0123456789]+/")) )

(make-ss-prob :name 'form19 :metafields '((method "post") (url nil)
	      (comment "server accepts an invalid primary_interest. bypass length restriction on password"))
 :phi '(and 
	 (= (var "Page") "")
	 (lte (len ?user_email) 255)
	 ;(= ?user_email "first@first.com")
	 (lte (len ?user_email_confirm) 255)
	 ;(= ?user_email_confirm "first@first.com")
	 (lte (len ?password) 32)
	 (gte (len ?password) 5)
	 ;(= ?password "")   unsat if this is here
	 (lte (len ?password_confirm) 32)
	 (gte (len ?password_confirm) 5)
	 (= ?password ?password_confirm)
	 ; (= ?password_confirm "") unsat if this is here
	 (lte (len ?first_name) 30)
	 (= ?first_name "first")
	 (lte (len ?last_name) 30)
	 (= ?last_name "last")
	 (= ?accept_terms "true")
	 (= ?country_code "10")
	 (= ?primary_interest "AC00")
	 (in ?receive_updates "/true/")
	 (in ?accept_terms "/true/")
	 (in ?country_code "/10|13|66|19|8|16|12|17|11|18|14|22|21|20|23|37|30|26|25|41|27|42|32|33|38|35|24|40|39|36|110|34|29|28|31|120|52|43|57|127|46|214|51|53|58|44|54|122|45|47|50|55|49|103|56|59|60|63|62|64|65|223|67|69|209|93|71|68|73|74|77|79|76|75|80|81|86|176|215|82|90|85|61|87|88|94|89|84|92|97|96|91|98|99|104|101|102|100|105|113|109|106|112|111|107|108|114|115|117|116|128|118|121|126|119|129|138|130|135|134|139|132|136|137|149|145|143|157|159|156|146|154|144|151|152|155|245|158|78|142|141|148|417|153|140|160|147|161|170|169|15|167|162|172|166|163|165|171|164|124|150|168|173|179|186|184|174|177|187|175|178|182|180|185|183|188|189|190|191|192|199|123|131|181|243|204|208|193|205|246|195|203|198|202|200|194|206|247|95|125|72|133|236|196|207|201|211|197|48|210|212|227|218|228|217|216|219|222|225|221|224|220|213|226|230|229|9|83|232|233|231|234|241|235|237|240|238|239|242|70|244|248|249/")
	 (in ?primary_interest "/BUSI|AC00|BA00|EC00|FI00|BA51|BA10|BA80|BA90|BAA0|FI60|BA60|CHEM|CH10|CHB0|CG00|CH00|CHD0|CH19|CH20|FO00|CH30|CH70|CH80|CH60|CH90|CH15|CH63|EART|AG00|AQ10|ES50|ES00|EN60|ES10|ES30|EDUC|ED00|ED20|ED70|ENGI|AR00|BE00|CE00|EE20|EE30|EE00|MS40|CE40|CE42|IE00|ME00|EE85|SSOC|HI03|AN00|AH00|AA00|CL00|CO00|EC50|PS32|HI00|GE00|LG00|LT00|PL00|PO00|RE00|SS00|SO00|SP30|SO40|COMP|CS00|ED30|CS30|CS50|LAW0|LA00|LA70|LIFE|LS10|LS69|AN30|LS35|LS30|ES1B|LS60|LS33|LS00|LS50|LSA0|LS90|LS80|MAST|MA20|ST20|ST70|STB0|MA00|MA80|ST10|ST40|ST00|ST30|MEDI|MD20|MD30|HED0|MD40|MDD1|DN00|MD60|MD70|MD80|ST37|MD02|MD90|MDB0|HE10|MDC0|MDP0|MD17|ED72|MD00|HE70|MDF0|NU00|HE80|MDG0|HEB0|MDH0|MDJ1|DN20|DN30|MDU6|MDK0|MDL0|MDM0|MDN0|HE50|MDE0|MDR0|MDU0|MDU2|MDW0|VE00|PHYS|PH10|PH90|PH00|PHG1|PH60|PH80|POLY|MSB0|MS00|NT10|PY00|MSF0|MSB0|PSYC|PS7A|PS10|PS70|PS30|PS60|PS00|PS80|PS40/")   )
 :types '(type 
	 (IN (var "Page") "/[a-zA-Z]*/" )
	 (IN ?user_email "/[\\.@cfimorst]+/")
	 (IN ?user_email_confirm "/[\\.@cfimorst]+/")
	 (IN ?password "/[a-zA-Z]*/")
	 (IN ?password_confirm "/[a-zA-Z]*/")
	 (IN ?first_name "/[first]+/")
	 (IN ?last_name "/[alst]+/")
	 (IN ?receive_updates "/[ertu]+/")
	 (IN ?accept_terms "/[ertu]+/")
	 (IN ?country_code "/[0123456789]+/")
	 (IN ?primary_interest "/[0123456789ABCDEFGHIJKLMNOPQRSTUVWY]+/")))

; bug in Hampi makes this unsolvable for ssn
(make-ss-prob :name 'form20 :metafields '((method "post") (url "http://www.garena.com/user/register.php")
	      (comment "- bypass restriction on country codes and enter an invalid country XX
- bypass gender restrictions (0/1) to supply a bogus value 22"))
 :phi '(and 
	 (= ?email "a@a.com")
	 (lte (len ?username) 16)
	 ;(= ?username "a1")
	;(gt (len ?username) 5) 
	(= ?gender "2")
	 (= ?agree "null")
	 (= ?location "US")
	 (in ?gender "/1|2/")
	 (in ?agree "/null/")
	 (in ?location "/US|AF|AL|DZ|AS|AD|AO|AI|AQ|AG|AR|AM|AW|AU|AT|AZ|BS|BH|BD|BB|BY|BE|BZ|BJ|BM|BT|BO|BA|BW|BV|BR|IO|BN|BG|BF|BI|KH|CM|CA|CV|KY|CF|TD|CL|CN|CX|CC|CO|KM|CG|CD|CK|CR|CI|HR|CU|CY|CZ|CS|DK|DJ|DM|DO|TP|EC|EG|SV|GQ|ER|EE|ET|EU|FK|FO|FJ|FI|FR|FX|GF|PF|TF|GA|GM|GE|DE|GH|GI|GR|GL|GD|GP|GU|GT|GN|GW|GY|HT|HM|VA|HN|HK|HU|IS|IN|ID|IR|IQ|IE|IL|IT|JM|JP|JO|KZ|KE|KI|KP|KR|KW|KG|LA|LV|LB|LS|LR|LY|LI|LT|LU|MO|MK|MG|MW|MY|MV|ML|MT|MH|MQ|MR|MU|YT|MX|FM|MD|MC|MN|ME|MS|MA|MZ|MM|NA|NR|NP|NL|AN|NC|NZ|NI|NE|NG|NU|NF|MP|NO|OM|PK|PW|PS|PA|PG|PY|PE|PH|PN|PL|PT|PR|QA|RE|RO|RU|RW|SH|KN|LC|PM|VC|WS|SM|ST|SA|RS|SN|SC|SL|SG|SK|SI|SB|SO|ZA|GS|ES|LK|SD|SR|SJ|SZ|SE|CH|SY|TW|TJ|TZ|TH|TG|TK|TO|TT|TN|TR|TM|TC|TV|UG|UA|AE|UK|US|UM|UY|UZ|VU|VE|VN|VG|VI|WF|EH|YE|ZM|ZW/"))
 :space '(gt (len ?username) 5)
 :types '(type 
	 (IN ?email "/[\\.@acmo]+/")
	 (IN ?username "/[\\-xX0-9a-f]+/")
	 (IN ?password "/[a-zA-Z]+/")
	 (IN ?confirm_password "/[a-zA-Z]+/")
	 (IN ?gender "/[12]+/")
	 (IN ?agree "/[a-zA-Z]+/")
	 (IN ?location "/[ABCDEFGHIJKLMNOPQRSTUVWXYZ]+/")))

(make-ss-prob :name 'real1
 :phi '(and 
	(= ?selProducts "")
	(= ?FlgFirstTimeVisit "1")
	(= ?hdnWarranty "12.93")
	(= ?hdnShipping "")
	(lte ?qty-8661 100)
	(NOT (lt 37 ?qty-8661 )) 
	(= ?Checkout "Checkout Now"))

 :types `(type 
	 (IN ?selProducts "/[a-zA-Z]*/" )
	 (IN ?FlgFirstTimeVisit "/[\\-xX0-9a-f]*/" )
	 (IN ?hdnWarranty "/[\\.1239]*/" )
	 (IN ?hdnShipping "/[a-zA-Z]*/" )))
	 ;(IN ?qty-8661 "/[\\-xX0-9a-f]*/")))

(make-ss-prob :name 'real2
  :phi '(and 
	 (lte (len ?ToType) 3)
	 (lte (len ?Amount) 9)
	 (= ?FromAccount "32008-001")
	 (in ?FromAccount "/32008-000|32008-001/")
	 (in ?ToAccount "/32008|32008/")
	 (OR (= ?Submit1 "Transfer") (= ?Reset1 "Clear")))
  :types '(type 
	 (IN ?ToType "/[a-zA-Z0-9]*/")
	 (IN ?Amount "/[a-zA-Z0-9]*/")   ; was typo
	 (IN ?FromAccount "/[0-9\\-]*/") ; was typo
	 (IN ?ToAccount "/[0-9]*/")
	 (IN ?Submit1 "[Transfer]*")
	 (IN ?Reset1 "[Clear]*"))
  :space '(and (in ?fromaccount "/32008-000|32008-001|47001-000|47001-001/")))

(make-ss-prob :name 'white1
 ;:variantstatus '((4 :inconsistent) )
 :phi '(and 
	(not (= (var "action") "redirect")) 
	(or (and (isset (var "user")) (isset (var "password"))) 
	    (and (isset (var "admin")) (isset (var "passwordDB")))) 
	(and (isset (var "admin")) (isset (var "passwordDB"))) 
	(not (or (not (var "subject")) 
	         (not (var "titletext")))) 
	(= (var "break") 1) 
	(not (= (var "break") 2)) 
	(= (var "break") 1) 
	(not (= (var "break") 2)) 
	(not (var "catid")) 
	(not (not (empty ""))) 
	(not (not (empty ""))) 
	(not (not (empty ""))) 
	(var "post")))

))

