(defhier "Root" (tags)
	(defhier "Applications" (tags application)
		(defhier "Distributed Systems" (tags distributed))
		(defhier "Security" (tags security)
			(defhier "Authorization" (tags authorization))
			(defhier "Privacy" (tags privacy))
			(defhier "Trust Management" (tags trustmanagement)))
		(defhier "Semantic Web" (tags semanticweb))
		(defhier "Logical Spreadsheets" (tags spreadsheet)))
	(defhier "Reasoning" (tags reasoning)
		(defhier "Abduction" (tags abduction))
		(defhier "Combination Procedures" (tags combination reasoning)
			(defhier "Architectures" (tags combination architecture)))
		(defhier "Databases" (tags database reasoning))
		(defhier "Deduction" (tags deduction reasoning)
			(defhier "Abstraction" (tags abstraction deduction))
			(defhier "Calculi" (tags calculus deduction))
			(defhier "Comparative Analysis" (tags comparativeanalysis))
			(defhier "Indexing" (tags indexing deduction))
			(defhier "Model-Guided" (tags modelguided))
			(defhier "Orderings" (tags ordering))
			(defhier "Architectures" (tags deduction architecture))
			(defhier "Applications" (tags deduction application))
			(defhier "Attachments" (tags deduction combination)))
		(defhier "Context Free Grammars" (tags contextfreegrammar))
		(defhier "Description Logic" (tags descriptionlogic reasoning))
		(defhier "Induction" (tags induction reasoning))
		(defhier "Logic Programming" (tags logicprogramming reasoning)
			(defhier "Constraint Logic Programming" (tags constraintlogicprogramming)))
		(defhier "Nonmonotonic" (tags reasoning nonmon))
		(defhier "Paraconsistency" (tags paraconsistency))
		(defhier "Reformulation" (tags transformation)
			(defhier "Model-Based" (tags modelbased)
				(defhier "Characteristic Models" (tags characteristicmodels))))
		(defhier "Satisfiability" (tags reasoning satisfiability)
			(defhier "Model Building" (tags satisfiability firstorder))
			(defhier "SAT Solving" (tags satisfiability propositional)))
		(defhier "Semantic Methods" (tags semanticmethod)
			(defhier "Case-Based" (tags casebased))
			(defhier "Graphical" (tags graphical)))
		(defhier "Temporal" (tags temporal reasoning)
			(defhier "Model Checking" (tags modelchecking))
			(defhier "Behavioral Goals" (tags behavioralgoals))
			(defhier "Hypothetical Temporal DB Queries" (tags hypothetical temporal database))
			(defhier "Planning" (tags planning)
				(defhier "Deductive" (tags planning deduction))
				(defhier "Sensing" (tags planning sensor))
				(defhier "Recursive" (tags planning recursion))
				(defhier "Historical" (tags planning historical)))))
	(defhier "Representation" (tags representation)
		(defhier "Classical" (tags classical representation)
			(defhier "Herbrand Logic" (tags herbrandlogic representation)))
		(defhier "Constraint Satisfaction" (tags constraintsatisfaction representation)
			(defhier "Object Oriented Languages" (objectoriented constraintsatisfaction)))
		(defhier "Databases" (tags representation database))
		(defhier "Nonmonotonic" (tags nonmon representation))
		(defhier "Paraconsistency" (tags paraconsistency representation)))
	(defhier "Textbooks" (tags textbook))
	(defhier "Websites" (tags website)))
